workflows:
  android-debug:
    name: Android Debug APK
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Prepare project
        script: |
          echo "Working dir: $(pwd)"
          if [ ! -d "android" ]; then
            flutter create . --platforms=android
          fi

          # Ensure Gradle has enough memory
          mkdir -p android
          echo "org.gradle.jvmargs=-Xmx3g -Dkotlin.daemon.jvm.options=-Xmx1g" >> android/gradle.properties
          echo "android.enableJetifier=true" >> android/gradle.properties
          echo "android.useAndroidX=true" >> android/gradle.properties

          flutter clean
          flutter pub get

      - name: Build debug APK (arm64 only to reduce memory)
        script: |
          flutter build apk --debug --target-platform=android-arm64

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
